name: 버그
description: 문제가 생겼을 때 사용합니다.
title: "fix: "
labels: ["bug"]
body:
  - type: textarea
    id: todo
    attributes:
      label: 무엇이 문제인가요?
      placeholder: 예) 로그인 버튼을 눌러도 다음 화면으로 이동하지 않음
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: 참고
      placeholder: 예) 스크린샷, 에러 메시지, 관련 파일
